//
//                           SimuLTE
//
// This file is part of a software released under the license included in file
// "license.pdf". This license can be also found at http://www.ltesimulator.com/
// The above file and the present reference are part of the software itself,
// and cannot be removed from it.
//

import stack.rlc.packet.LteRlcSdu;

cplusplus {{
  #include "stack/rlc/packet/LteRlcSdu.h"
}}

// packet LteRlcSdu { @existingClass; }

packet LteRlcAmSdu extends LteRlcSdu
{
}