//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
//

cplusplus {{
#include "common/LteCommon.h"
}}


struct Lambda
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct RemoteTable
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct LtePhyFrameTable
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct LteNodeTable
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct LteSubFrameTypeTable
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct AbsStatusInfoMsg
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct BandLimit
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct RemoteUnitPhyData
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct EnbInfo
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct UeInfo
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct UeAllocationInfo
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct QCIParameters
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct ApplicationTable
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct SchedDisciplineTable
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct TxTable
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct TxDirectionTable
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct FeedbackRequest
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct FeedbackGeneratorTypeTable
{
    @existingClass;
    @opaque;
    @toString(.str());
}

struct DeploymentScenarioMapping
{
    @existingClass;
    @opaque;
    @toString(.str());
}


class X2InformationElement
{
    @existingClass;
    @opaque;
    @toString(.str());
}

class LteMacBuffer
{
    @existingClass;
    @opaque;
    @toString(.str());
}

class LteMacQueue
{
    @existingClass;
    @opaque;
    @toString(.str());
}

class MacControlElement
{
    @existingClass;
    @opaque;
    @toString(.str());
}

class LteMacPdu
{
    @existingClass;
    @opaque;
    @toString(.str());
}

class LteBinder
{
    @existingClass;
    @opaque;
    @toString(.str());
}

class LteCellInfo
{
    @existingClass;
    @opaque;
    @toString(.str());
}

class LteMacEnb
{
    @existingClass;
    @opaque;
    @toString(.str());
}

class LteMacBase
{
    @existingClass;
    @opaque;
    @toString(.str());
}

class LtePhyBase
{
    @existingClass;
    @opaque;
    @toString(.str());
}


class LteRealisticChannelModel
{
    @existingClass;
    @opaque;
    @toString(.str());
}

//class LteControlInfo
//{
//    @existingClass;
//    @opaque;
//    @toString(.str());
//}

class ExtCell
{
    @existingClass;
    @opaque;
    @toString(.str());
}
 